const sentenceData = {
  week1: [
    // 1번
    {
      id: 'sentence1',
      level: 1,
      isFinal: false,
      korean: '디저트를 준다.',
      chinese: {
        hanzi: ['送', '甜点'],
        pinyin: ['sòng', 'tiándiǎn'],
      },
    },
    {
      id: 'sentence1',
      level: 2,
      isFinal: false,
      korean: '디저트를 무료로 준다.',
      chinese: {
        hanzi: ['免费', '送', '甜点'],
        pinyin: ['miǎnfèi', 'sòng', 'tiándiǎn'],
      },
    },
    {
      id: 'sentence1',
      level: 3,
      isFinal: false,
      korean: '오늘 디저트를 무료로 준대.',
      chinese: {
        hanzi: ['今天', '免费', '送', '甜点'],
        pinyin: ['jīntiān', 'miǎnfèi', 'sòng', 'tiándiǎn'],
      },
    },
    {
      id: 'sentence1',
      level: 4,
      isFinal: false,
      korean: '그 식당은 오늘 디저트를 무료로 준대.',
      chinese: {
        hanzi: ['那', '家', '餐厅', '今天', '免费', '送', '甜点'],
        pinyin: [
          'nà',
          'jiā',
          'cāntīng',
          'jīntiān',
          'miǎnfèi',
          'sòng',
          'tiándiǎn',
        ],
      },
    },
    {
      id: 'sentence1',
      level: 5,
      isFinal: true,
      korean: 'A: 듣자하니 그 식당이 오늘 디저트를 무료로 준대.',
      chinese: {
        hanzi: ['听说', '那', '家', '餐厅', '今天', '免费', '送', '甜点'],
        pinyin: [
          'tīngshuō',
          'nà',
          'jiā',
          'cāntīng',
          'jīntiān',
          'miǎnfèi',
          'sòng',
          'tiándiǎn',
        ],
      },
    },
    {
      id: 'sentence1',
      level: 6,
      isFinal: false,
      korean: '한번 보다(좀 보다)',
      chinese: {
        hanzi: ['看看'],
        pinyin: ['kànkan'],
      },
    },
    {
      id: 'sentence1',
      level: 7,
      isFinal: false,
      korean: '한번 보다',
      chinese: {
        hanzi: ['看看', '吧'],
        pinyin: ['kànkan', 'ba'],
      },
    },
    {
      id: 'sentence1',
      level: 8,
      isFinal: false,
      korean: '한번 보러 가자.',
      chinese: {
        hanzi: ['去', '看看', '吧'],
        pinyin: ['qù', 'kànkan', 'ba'],
      },
    },
    {
      id: 'sentence1',
      level: 9,
      isFinal: false,
      korean: '퇴근 후에 한번 보러 가자.',
      chinese: {
        hanzi: ['下班', '后', '去', '看看', '吧'],
        pinyin: ['xiàbān', 'hòu', 'qù', 'kànkan', 'ba'],
      },
    },
    {
      id: 'sentence1',
      level: 10,
      isFinal: false,
      korean: '우리 퇴근 후에 한번 보러 가자.',
      chinese: {
        hanzi: ['我们', '下班', '后', '去', '看看', '吧'],
        pinyin: ['wǒmen', 'xiàbān', 'hòu', 'qù', 'kànkan', 'ba'],
      },
    },
    {
      id: 'sentence1',
      level: 11,
      isFinal: false,
      korean: '그럼 우리 퇴근 후에 한번 보러 가자.',
      chinese: {
        hanzi: ['那', '我们', '下班', '后', '去', '看看', '吧'],
        pinyin: ['nà', 'wǒmen', 'xiàbān', 'hòu', 'qù', 'kànkan', 'ba'],
      },
    },
    {
      id: 'sentence1',
      level: 12,
      isFinal: true,
      korean: 'B: 진짜야? 그럼 우리 퇴근 후에 한번 보러 가자.',
      chinese: {
        hanzi: ['真的', '假的', '那', '我们', '下班', '后', '去', '看看', '吧'],
        pinyin: [
          'zhen de',
          'jia de',
          'nà',
          'wǒmen',
          'xiàbān',
          'hòu',
          'qù',
          'kànkan',
          'ba',
        ],
      },
    },

    // 2번
    {
      id: 'sentence2',
      level: 1,
      isFinal: false,
      korean: '새 직장을 찾았다.',
      chinese: {
        hanzi: ['找到', '新', '工作'],
        pinyin: ['zhǎodào', 'xīn', 'gōngzuò'],
      },
    },
    {
      id: 'sentence2',
      level: 2,
      isFinal: false,
      korean: '이미 새 직장을 찾았다.',
      chinese: {
        hanzi: ['已经', '找到', '新', '工作了'],
        pinyin: ['yǐjing', 'zhǎodào', 'xīn', 'gōngzuò le'],
      },
    },
    {
      id: 'sentence2',
      level: 3,
      isFinal: false,
      korean: '그는 이미 새 직장을 찾았다.',
      chinese: {
        hanzi: ['他', '已经', '找到', '新', '工作了'],
        pinyin: ['tā', 'yǐjing', 'zhǎodào', 'xīn', 'gōngzuò le'],
      },
    },
    {
      id: 'sentence2',
      level: 4,
      isFinal: true,
      korean: 'A: 듣자 하니 그는 이미 새 직장을 찾았다.',
      chinese: {
        hanzi: ['听说', '他', '已经', '找到', '新', '工作', '了'],
        pinyin: ['tīngshuō', 'tā', 'yǐjing', 'zhǎodào', 'xīn', 'gōngzuò', 'le'],
      },
    },
    {
      id: 'sentence2',
      level: 5,
      isFinal: false,
      korean: '찾았어.',
      chinese: {
        hanzi: ['找到', '了'],
        pinyin: ['zhǎodào', 'le'],
      },
    },
    {
      id: 'sentence2',
      level: 6,
      isFinal: false,
      korean: '벌써 찾았어?',
      chinese: {
        hanzi: ['就', '找到', '了'],
        pinyin: ['jiù', 'zhǎodào', 'le'],
      },
    },
    {
      id: 'sentence2',
      level: 7,
      isFinal: false,
      korean: '이렇게(그렇게) 빨리 벌써 찾았어?',
      chinese: {
        hanzi: ['这么', '快', '就', '找到', '了'],
        pinyin: ['zhème', 'kuài', 'jiù', 'zhǎodào', 'le'],
      },
    },
    {
      id: 'sentence2',
      level: 8,
      isFinal: true,
      korean: 'B: 그래? 이렇게(그렇게) 빨리 벌써 찾은 거야?',
      chinese: {
        hanzi: ['是吗', '这么', '快', '就', '找到', '了'],
        pinyin: ['shì ma', 'zhème', 'kuài', 'jiù', 'zhǎodào', 'le'],
      },
    },

    // 3번
    {
      id: 'sentence3',
      level: 1,
      isFinal: false,
      korean: '택시에 있어.',
      chinese: {
        hanzi: ['在', '出租车', '上'],
        pinyin: ['zài', 'chūzūchē', 'shàng'],
      },
    },
    {
      id: 'sentence3',
      level: 2,
      isFinal: false,
      korean: '택시에 둔 걸 까먹다.',
      chinese: {
        hanzi: ['忘在', '出租车', '上了'],
        pinyin: ['wàng zài', 'chūzūchē', 'shàng le'],
      },
    },
    {
      id: 'sentence3',
      level: 3,
      isFinal: false,
      korean: '휴대폰을 택시에 둔 걸 까먹다(까먹고 두고 내렸다)',
      chinese: {
        hanzi: ['把', '手机', '忘', '在', '出租车', '上了'],
        pinyin: ['bǎ', 'shǒujī', 'wàng', 'zài', 'chūzūchē', 'shàng le'],
      },
    },
    {
      id: 'sentence3',
      level: 4,
      isFinal: true,
      korean: 'A: 나는 휴대폰을 택시에 둔 걸 까먹다(까먹고 두고 내렸다)',
      chinese: {
        hanzi: ['我', '把', '手机', '忘', '在', '出租车', '上', '了'],
        pinyin: [
          'wǒ',
          'bǎ',
          'shǒujī',
          'wàng',
          'zài',
          'chūzūchē',
          'shàng',
          'le',
        ],
      },
    },
    {
      id: 'sentence3',
      level: 5,
      isFinal: false,
      korean: '어떡하지?',
      chinese: {
        hanzi: ['怎么办'],
        pinyin: ['zěnmebàn'],
      },
    },
    {
      id: 'sentence3',
      level: 6,
      isFinal: false,
      korean: '그럼 어떡하지?',
      chinese: {
        hanzi: ['那', '怎么办'],
        pinyin: ['nà', 'zěnmebàn'],
      },
    },
    {
      id: 'sentence3',
      level: 7,
      isFinal: true,
      korean: 'B: 아이고! 그럼 어떡하지?',
      chinese: {
        hanzi: ['哎呀', '那', '怎么办'],
        pinyin: ['āiyā', 'nà', 'zěnmebàn'],
      },
    },
    // 4번
    {
      id: 'sentence4',
      level: 1,
      isFinal: false,
      korean: '면접 날',
      chinese: {
        hanzi: ['面试', '的', '日子'],
        pinyin: ['miànshì', 'de', 'rìzi'],
      },
    },
    {
      id: 'sentence4',
      level: 2,
      isFinal: false,
      korean: '오늘은 면접 날이야.',
      chinese: {
        hanzi: ['今天', '是', '面试', '的', '日子'],
        pinyin: ['jīntiān', 'shì', 'miànshì', 'de', 'rìzi'],
      },
    },
    {
      id: 'sentence4',
      level: 3,
      isFinal: false,
      korean: '오늘이 면접 날인 걸 까먹었어.',
      chinese: {
        hanzi: ['忘了', '今天', '是', '面试', '的', '日子'],
        pinyin: ['wàng le', 'jīntiān', 'shì', 'miànshì', 'de', 'rìzi'],
      },
    },
    {
      id: 'sentence4',
      level: 4,
      isFinal: false,
      korean: '뜻밖에도 오늘이 면접 날인 걸 까먹었어.',
      chinese: {
        hanzi: ['居然', '忘', '了', '今天', '是', '面试', '的', '日子'],
        pinyin: [
          'jūrán',
          'wàng',
          'le',
          'jīntiān',
          'shì',
          'miànshì',
          'de',
          'rìzi',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 5,
      isFinal: true,
      korean: 'A: 그 사람은 (뜻밖에도) 오늘이 면접 날인 걸 까먹었대.',
      chinese: {
        hanzi: ['他', '居然', '忘', '了', '今天', '是', '面试', '的', '日子'],
        pinyin: [
          'tā',
          'jūrán',
          'wàng',
          'le',
          'jīntiān',
          'shì',
          'miànshì',
          'de',
          'rìzi',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 6,
      isFinal: false,
      korean: '중요한 일',
      chinese: {
        hanzi: ['重要的事'],
        pinyin: ['zhòngyào de shì'],
      },
    },
    {
      id: 'sentence4',
      level: 7,
      isFinal: false,
      korean: '이렇게(그렇게) 중요한 일',
      chinese: {
        hanzi: ['这么', '重要', '的', '事'],
        pinyin: ['zhème', 'zhòngyào', 'de', 'shì'],
      },
    },
    {
      id: 'sentence4',
      level: 8,
      isFinal: false,
      korean: '이렇게(그렇게) 중요한 일도 잊을 수 있어?',
      chinese: {
        hanzi: ['这么', '重要', '的', '事', '也', '能', '忘'],
        pinyin: ['zhème', 'zhòngyào', 'de', 'shì', 'yě', 'néng', 'wàng'],
      },
    },
    {
      id: 'sentence4',
      level: 9,
      isFinal: true,
      korean: 'B: 설마? 이렇게(그렇게) 중요한 일도 잊을 수 있어?',
      chinese: {
        hanzi: ['不会吧', '这么', '重要', '的', '事', '也', '能', '忘'],
        pinyin: [
          'bú huì ba',
          'zhème',
          'zhòngyào',
          'de',
          'shì',
          'yě',
          'néng',
          'wàng',
        ],
      },
    },

    // 5번
    {
      id: 'sentence5',
      level: 1,
      isFinal: false,
      korean: '1등을 하다',
      chinese: {
        hanzi: ['拿', '第', '一', '名'],
        pinyin: ['ná', 'dì', 'yī', 'míng'],
      },
    },
    {
      id: 'sentence5',
      level: 2,
      isFinal: false,
      korean: '1등을 했다.',
      chinese: {
        hanzi: ['拿了', '第', '一', '名'],
        pinyin: ['ná le', 'dì', 'yī', 'míng'],
      },
    },
    {
      id: 'sentence5',
      level: 3,
      isFinal: false,
      korean: '바로(단번에) 1등을 했다.',
      chinese: {
        hanzi: ['就', '拿', '了', '第', '一', '名'],
        pinyin: ['jiù', 'ná', 'le', 'dì', 'yī', 'míng'],
      },
    },
    {
      id: 'sentence5',
      level: 4,
      isFinal: false,
      korean: '대회에 참가하자마자 바로 1등을 했어.',
      chinese: {
        hanzi: ['参加', '比赛', '就', '拿', '了', '第', '一', '名'],
        pinyin: ['cānjiā', 'bǐsài', 'jiù', 'ná', 'le', 'dì', 'yī', 'míng'],
      },
    },
    {
      id: 'sentence5',
      level: 5,
      isFinal: false,
      korean: '처음 대회에 참가하자마자 바로 1등을 했어.',
      chinese: {
        hanzi: [
          '第',
          '一次',
          '参加',
          '比赛',
          '就',
          '拿',
          '了',
          '第',
          '一',
          '名',
        ],
        pinyin: [
          'dì',
          'yī cì',
          'cānjiā',
          'bǐsài',
          'jiù',
          'ná',
          'le',
          'dì',
          'yī',
          'míng',
        ],
      },
    },
    {
      id: 'sentence5',
      level: 6,
      isFinal: true,
      korean: 'A: 걔는 처음 대회에 참가하자마자 바로 1등을 했어.',
      chinese: {
        hanzi: [
          '他',
          '第',
          '一',
          '次',
          '参加',
          '比赛',
          '就',
          '拿',
          '了',
          '第',
          '一',
          '名',
        ],
        pinyin: [
          'tā',
          'dì',
          'yī',
          'cì',
          'cānjiā',
          'bǐsài',
          'jiù',
          'ná',
          'le',
          'dì',
          'yī',
          'míng',
        ],
      },
    },
    {
      id: 'sentence5',
      level: 7,
      isFinal: false,
      korean: '쉽지 않은데.',
      chinese: {
        hanzi: ['不', '简单'],
        pinyin: ['bù', 'jiǎndān'],
      },
    },
    {
      id: 'sentence5',
      level: 8,
      isFinal: false,
      korean: '진짜 쉽지 않은데.',
      chinese: {
        hanzi: ['真', '不', '简单'],
        pinyin: ['zhēn', 'bù', 'jiǎndān'],
      },
    },
    {
      id: 'sentence5',
      level: 9,
      isFinal: false,
      korean: '대단하다! 진짜 쉽지 않은데.',
      chinese: {
        hanzi: ['厉害', '真', '不', '简单'],
        pinyin: ['lìhai', 'zhēn', 'bù', 'jiǎndān'],
      },
    },
    {
      id: 'sentence5',
      level: 10,
      isFinal: true,
      korean: 'B: 너무 대단하다! 진짜 쉽지 않은데.',
      chinese: {
        hanzi: ['太', '厉害', '了', '真', '不', '简单'],
        pinyin: ['tài', 'lìhai', 'le', 'zhēn', 'bù', 'jiǎndān'],
      },
    },
  ],

  week2: [
    // 11번
    {
      id: 'sentence6',
      level: 1,
      isFinal: false,
      korean: '경기에 참가하다.',
      chinese: {
        hanzi: ['参加', '比赛'],
        pinyin: ['cānjiā', 'bǐsài'],
      },
    },
    {
      id: 'sentence6',
      level: 2,
      isFinal: false,
      korean: '경기에 참가하지 않다.',
      chinese: {
        hanzi: ['不', '参加', '比赛'],
        pinyin: ['bù', 'cānjiā', 'bǐsài'],
      },
    },
    {
      id: 'sentence6',
      level: 3,
      isFinal: false,
      korean: '(이제) 경기에 참가하지 않게 되었다.',
      chinese: {
        hanzi: ['不', '参加', '比赛', '了'],
        pinyin: ['bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 4,
      isFinal: false,
      korean: '(이제) 경기에 참가하지 않는 거야?',
      chinese: {
        hanzi: ['是不是', '不', '参加', '比赛', '了'],
        pinyin: ['shì bu shì', 'bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 5,
      isFinal: true,
      korean: 'A: 걔는 (이제) 경기에 참가하지 않는 거야?',
      chinese: {
        hanzi: ['他', '是不是', '不', '参加', '比赛', '了'],
        pinyin: ['tā', 'shì bu shì', 'bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 6,
      isFinal: false,
      korean: '훈련에 오다.',
      chinese: {
        hanzi: ['来', '训练'],
        pinyin: ['lái', 'xùnliàn'],
      },
    },
    {
      id: 'sentence6',
      level: 7,
      isFinal: false,
      korean: '훈련에 안 왔다.',
      chinese: {
        hanzi: ['没', '来', '训练'],
        pinyin: ['méi', 'lái', 'xùnliàn'],
      },
    },
    {
      id: 'sentence6',
      level: 8,
      isFinal: false,
      korean: '이렇게 오랫동안 훈련에 안 나왔다.',
      chinese: {
        hanzi: ['这么', '久', '没', '来', '训练了'],
        pinyin: ['zhème', 'jiǔ', 'méi', 'lái', 'xùnliàn le'],
      },
    },
    {
      id: 'sentence6',
      level: 9,
      isFinal: false,
      korean: '이미 이렇게 오래 훈련에 안 나왔는데, ......',
      chinese: {
        hanzi: ['都', '这么', '久', '没', '来', '训练了, ......'],
        pinyin: ['dōu', 'zhème', 'jiǔ', 'méi', 'lái', 'xùnliàn le'],
      },
    },
    {
      id: 'sentence6',
      level: 10,
      isFinal: false,
      korean: '이미 이렇게 오래 훈련에 안 나왔는데, 분명 그렇지.',
      chinese: {
        hanzi: ['都', '这么', '久', '没', '来', '训练', '了', '肯定', '是'],
        pinyin: [
          'dōu',
          'zhème',
          'jiǔ',
          'méi',
          'lái',
          'xùnliàn',
          'le',
          'kěndìng',
          'shì',
        ],
      },
    },
    {
      id: 'sentence6',
      level: 11,
      isFinal: true,
      korean: 'B: 너 생각엔? 이미 이렇게 오래 훈련에 안 나왔는데, 분명 그렇지.',
      chinese: {
        hanzi: [
          '你',
          '说',
          '呢',
          '都',
          '这么',
          '久',
          '没',
          '来',
          '训练',
          '了',
          '肯定',
          '是',
        ],
        pinyin: [
          'nǐ',
          'shuō',
          'ne',
          'dōu',
          'zhème',
          'jiǔ',
          'méi',
          'lái',
          'xùnliàn',
          'le',
          'kěndìng',
          'shì',
        ],
      },
    },

    // 2번
    {
      id: 'sentence7',
      level: 1,
      isFinal: false,
      korean: '시간 있어.',
      chinese: {
        hanzi: ['有', '空'],
        pinyin: ['yǒu', 'kòng'],
      },
    },
    {
      id: 'sentence7',
      level: 2,
      isFinal: false,
      korean: '시간 있어?',
      chinese: {
        hanzi: ['有', '空', '吗'],
        pinyin: ['yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 3,
      isFinal: false,
      korean: '내일 시간 있어?',
      chinese: {
        hanzi: ['明天', '有', '空', '吗'],
        pinyin: ['míngtiān', 'yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 4,
      isFinal: true,
      korean: 'A: 너 내일 시간 있어?',
      chinese: {
        hanzi: ['你', '明天', '有', '空', '吗'],
        pinyin: ['nǐ', 'míngtiān', 'yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 5,
      isFinal: false,
      korean: '일정을 보다.',
      chinese: {
        hanzi: ['看', '日程'],
        pinyin: ['kàn', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 6,
      isFinal: false,
      korean: '일정 한번 볼게.',
      chinese: {
        hanzi: ['看看', '日程'],
        pinyin: ['kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 7,
      isFinal: false,
      korean: '나 일정 한번 볼게.',
      chinese: {
        hanzi: ['我', '看看', '日程'],
        pinyin: ['wǒ', 'kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 8,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程'],
        pinyin: ['nà ge', 'wǒ', 'kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 9,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게. 오후에 돼.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程', '下午', '可以'],
        pinyin: ['nà ge', 'wǒ', 'kànkan', 'rìchéng', 'xiàwǔ', 'kěyǐ'],
      },
    },
    {
      id: 'sentence7',
      level: 10,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게. 오후에 될 것 같아.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程', '下午', '好像', '可以'],
        pinyin: [
          'nà ge',
          'wǒ',
          'kànkan',
          'rìchéng',
          'xiàwǔ',
          'hǎoxiàng',
          'kěyǐ',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 11,
      isFinal: true,
      korean: 'B: 내일… 그… 나 일정 한번 볼게. 오후에 될 것 같아.',
      chinese: {
        hanzi: [
          '明天啊... ',
          '那个',
          '我',
          '看看',
          '日程',
          '下午',
          '好像',
          '可以',
        ],
        pinyin: [
          'míngtiān a',
          'nà ge',
          'wǒ',
          'kànkan',
          'rìchéng',
          'xiàwǔ',
          'hǎoxiàng',
          'kěyǐ',
        ],
      },
    },

    // 3번
    {
      id: 'sentence8',
      level: 1,
      isFinal: false,
      korean: '지금 하는 일',
      chinese: {
        hanzi: ['现在', '的', '工作'],
        pinyin: ['xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 2,
      isFinal: false,
      korean: '지금 하는 일을 좋아해.',
      chinese: {
        hanzi: ['喜欢', '现在', '的', '工作'],
        pinyin: ['xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 3,
      isFinal: false,
      korean: '지금 하는 일을 좋아해?',
      chinese: {
        hanzi: ['喜不喜欢', '现在', '的', '工作'],
        pinyin: ['xǐ bu xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 4,
      isFinal: true,
      korean: 'A: 너 지금 하는 일을 좋아해?(좋아해 안 좋아해?)',
      chinese: {
        hanzi: ['你', '喜', '不', '喜欢', '现在', '的', '工作'],
        pinyin: ['nǐ', 'xǐ', 'bu', 'xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 5,
      isFinal: false,
      korean: '좋은 점도 있고 나쁜 점도 있어.',
      chinese: {
        hanzi: ['有好有坏'],
        pinyin: ['yǒu hǎo yǒu huài'],
      },
    },
    {
      id: 'sentence8',
      level: 6,
      isFinal: false,
      korean: '좋은 점도 있고 나쁜 점도 있지.',
      chinese: {
        hanzi: ['有好', '有坏', '吧'],
        pinyin: ['yǒu hǎo', 'yǒu huài', 'ba'],
      },
    },
    {
      id: 'sentence8',
      level: 7,
      isFinal: true,
      korean: 'B: 어떻게 말해야 할까… 좋은 점도 있고 나쁜 점도 있지.',
      chinese: {
        hanzi: ['怎么', '说', '呢', '有好', '有坏', '吧'],
        pinyin: ['zěnme', 'shuō', 'ne', 'yǒu hǎo', 'yǒu huài', 'ba'],
      },
    },
    // 4번
    {
      id: 'sentence9',
      level: 1,
      isFinal: false,
      korean: '여행 가다.',
      chinese: {
        hanzi: ['去', '旅行'],
        pinyin: ['qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 2,
      isFinal: false,
      korean: '같이 여행 가다.',
      chinese: {
        hanzi: ['一起', '去', '旅行'],
        pinyin: ['yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 3,
      isFinal: false,
      korean: '같이 여행 갈래?',
      chinese: {
        hanzi: ['要不要', '一起', '去', '旅行'],
        pinyin: ['yào bu yào', 'yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 4,
      isFinal: true,
      korean: 'A: 주말에 같이 여행 갈래?',
      chinese: {
        hanzi: ['周末', '要不要', '一起', '去', '旅行'],
        pinyin: ['zhōumò', 'yào bu yào', 'yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 5,
      isFinal: false,
      korean: '시간을 좀 보다.',
      chinese: {
        hanzi: ['看看', '时间'],
        pinyin: ['kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 6,
      isFinal: false,
      korean: '시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['得', '看看', '时间'],
        pinyin: ['děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 7,
      isFinal: false,
      korean: '나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['我', '得', '看看', '时间'],
        pinyin: ['wǒ', 'děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 8,
      isFinal: false,
      korean: '이건 말이지…… 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['这个嘛', '我', '得', '看看', '时间'],
        pinyin: ['zhè ge ma', 'wǒ', 'děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 9,
      isFinal: false,
      korean: '이건 말이지…… 일이 좀 많아서, 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['这个嘛', '事情', '有点', '多', '我', '得', '看看', '时间'],
        pinyin: [
          'zhè ge ma',
          'shìqing',
          'yǒudiǎn',
          'duō',
          'wǒ',
          'děi',
          'kànkan',
          'shíjiān',
        ],
      },
    },
    {
      id: 'sentence9',
      level: 10,
      isFinal: true,
      korean: 'B: 이건 말이지…… 요즘 일이 좀 많아서, 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: [
          '这个嘛',
          '最近',
          '事情',
          '有点',
          '多',
          '我',
          '得',
          '看看',
          '时间',
        ],
        pinyin: [
          'zhè ge ma',
          'zuìjìn',
          'shìqing',
          'yǒudiǎn',
          'duō',
          'wǒ',
          'děi',
          'kànkan',
          'shíjiān',
        ],
      },
    },
    // 5번
    {
      id: 'sentence10',
      level: 1,
      isFinal: false,
      korean: '나를 도와줘.',
      chinese: {
        hanzi: ['帮', '我'],
        pinyin: ['bāng', 'wǒ'],
      },
    },
    {
      id: 'sentence10',
      level: 2,
      isFinal: false,
      korean: '나를 좀 도와줘.',
      chinese: {
        hanzi: ['帮', '我', '一下'],
        pinyin: ['bāng', 'wǒ', 'yíxià'],
      },
    },
    {
      id: 'sentence10',
      level: 3,
      isFinal: false,
      korean: '나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['能', '帮', '我', '一下', '吗'],
        pinyin: ['néng', 'bāng', 'wǒ', 'yíxià', 'ma'],
      },
    },
    {
      id: 'sentence10',
      level: 4,
      isFinal: false,
      korean: '너는 나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['你', '能', '帮', '我', '一下', '吗'],
        pinyin: ['nǐ', 'néng', 'bāng', 'wǒ', 'yíxià', 'ma'],
      },
    },
    {
      id: 'sentence10',
      level: 5,
      isFinal: true,
      korean: 'A: 이번 주말에 너는 나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['这', '个', '周末', '你', '能', '帮', '我', '一下', '吗'],
        pinyin: [
          'zhè',
          'ge',
          'zhōumò',
          'nǐ',
          'néng',
          'bāng',
          'wǒ',
          'yíxià',
          'ma',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 6,
      isFinal: false,
      korean: '좀 생각해 보다.',
      chinese: {
        hanzi: ['想想'],
        pinyin: ['xiǎngxiang'],
      },
    },
    {
      id: 'sentence10',
      level: 7,
      isFinal: false,
      korean: '내가 좀 생각해볼게(내가 좀 생각하게 해줘)',
      chinese: {
        hanzi: ['让', '我', '想想'],
        pinyin: ['ràng', 'wǒ', 'xiǎngxiang'],
      },
    },
    {
      id: 'sentence10',
      level: 8,
      isFinal: false,
      korean: '시간이 맞다(시간이 된다).',
      chinese: {
        hanzi: ['时间', '来得及'],
        pinyin: ['shíjiān', 'lái de jí'],
      },
    },
    {
      id: 'sentence10',
      level: 9,
      isFinal: false,
      korean: '만약 시간이 맞다면……',
      chinese: {
        hanzi: ['如果', '时间', '来得及', '的话'],
        pinyin: ['rúguǒ', 'shíjiān', 'lái de jí', 'de huà'],
      },
    },
    {
      id: 'sentence10',
      level: 10,
      isFinal: false,
      korean: '내가 좀 생각해볼게… 만약 시간이 맞다면……',
      chinese: {
        hanzi: ['让', '我', '想想', '如果', '时间', '来得及', '的话'],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 11,
      isFinal: false,
      korean: '내가 좀 생각해볼게… 만약 시간이 맞으면 가능해.',
      chinese: {
        hanzi: ['让', '我', '想想', '如果', '时间', '来得及', '的话', '可以'],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
          'kěyǐ',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 12,
      isFinal: true,
      korean: 'B: 내가 좀 생각해볼게… 만약 시간이 맞으면 가능해.',
      chinese: {
        hanzi: [
          '让',
          '我',
          '想想',
          '如果',
          '时间',
          '来得及',
          '的话',
          '应该',
          '可以',
        ],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
          'yīnggāi',
          'kěyǐ',
        ],
      },
    },
  ],

  week3: [
    // 31번
    {
      id: 'sentence11',
      level: 1,
      isFinal: false,
      korean: '비가 와.',
      chinese: {
        hanzi: ['下雨', '了'],
        pinyin: ['xià yǔ', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 2,
      isFinal: false,
      korean: '오늘 비가 와.',
      chinese: {
        hanzi: ['今天', '下雨', '了'],
        pinyin: ['jīntiān', 'xià yǔ', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 3,
      isFinal: false,
      korean: '오늘 비 오는데 그래도……',
      chinese: {
        hanzi: ['今天', '下雨', '了', '还'],
        pinyin: ['jīntiān', 'xià yǔ', 'le', 'hái'],
      },
    },
    {
      id: 'sentence11',
      level: 4,
      isFinal: false,
      korean: '오늘 비 오는데 그래도 나가?',
      chinese: {
        hanzi: ['今天', '下雨', '了', '还', '出去', '吗'],
        pinyin: ['jīntiān', 'xià yǔ', 'le', 'hái', 'chūqù', 'ma'],
      },
    },
    {
      id: 'sentence11',
      level: 5,
      isFinal: true,
      korean: 'A: 오늘 비 오는데 그래도 나갈 거야?',
      chinese: {
        hanzi: ['今天', '下', '雨', '了', '还', '要', '出去', '吗'],
        pinyin: ['jīntiān', 'xià', 'yǔ', 'le', 'hái', 'yào', 'chūqù', 'ma'],
      },
    },
    {
      id: 'sentence11',
      level: 6,
      isFinal: false,
      korean: '약속했어.',
      chinese: {
        hanzi: ['约好', '了'],
        pinyin: ['yuē hǎo', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 7,
      isFinal: false,
      korean: '이미 약속했어.',
      chinese: {
        hanzi: ['已经', '约好', '了'],
        pinyin: ['yǐjing', 'yuē hǎo', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 8,
      isFinal: true,
      korean: 'B: 어쨌든 이미 약속했잖아.',
      chinese: {
        hanzi: ['反正', '已经', '约', '好', '了'],
        pinyin: ['fǎnzhèng', 'yǐjing', 'yuē', 'hǎo', 'le'],
      },
    },

    // 2번
    {
      id: 'sentence12',
      level: 1,
      isFinal: false,
      korean: '일 어때?',
      chinese: {
        hanzi: ['工作', '怎么样'],
        pinyin: ['gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 2,
      isFinal: false,
      korean: '이 일 어때?',
      chinese: {
        hanzi: ['这', '份', '工作', '怎么样'],
        pinyin: ['zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 3,
      isFinal: false,
      korean: '이 일에 대해 어떻게 생각해?',
      chinese: {
        hanzi: ['觉得', '这', '份', '工作', '怎么样'],
        pinyin: ['juéde', 'zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 4,
      isFinal: true,
      korean: 'A: 너는 이 일에 대해 어떻게 생각해?(너는 이 일이 어떤 것 같아?)',
      chinese: {
        hanzi: ['你', '觉得', '这', '份', '工作', '怎么样'],
        pinyin: ['nǐ', 'juéde', 'zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 5,
      isFinal: false,
      korean: '힘들어.',
      chinese: {
        hanzi: ['累'],
        pinyin: ['lèi'],
      },
    },
    {
      id: 'sentence12',
      level: 6,
      isFinal: false,
      korean: '좀 힘들어.',
      chinese: {
        hanzi: ['有点', '累'],
        pinyin: ['yǒudiǎn', 'lèi'],
      },
    },
    {
      id: 'sentence12',
      level: 7,
      isFinal: true,
      korean: 'B: 솔직히 말하면, 좀 힘들어.',
      chinese: {
        hanzi: ['说', '实话', '有点', '累'],
        pinyin: ['shuō', 'shíhuà', 'yǒudiǎn', 'lèi'],
      },
    },

    // 3번
    {
      id: 'sentence13',
      level: 1,
      isFinal: false,
      korean: '이 생각(이 아이디어)',
      chinese: {
        hanzi: ['这', '个', '想法'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ'],
      },
    },
    {
      id: 'sentence13',
      level: 2,
      isFinal: false,
      korean: '이 생각은 믿을 만해.',
      chinese: {
        hanzi: ['这', '个', '想法', '靠谱'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ', 'kàopǔ'],
      },
    },
    {
      id: 'sentence13',
      level: 3,
      isFinal: true,
      korean: 'A: 이 생각은 믿을 만해?',
      chinese: {
        hanzi: ['这', '个', '想法', '靠谱', '吗'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ', 'kàopǔ', 'ma'],
      },
    },
    {
      id: 'sentence13',
      level: 4,
      isFinal: false,
      korean: '위험이 있어.',
      chinese: {
        hanzi: ['有', '风险'],
        pinyin: ['yǒu', 'fēngxiǎn'],
      },
    },
    {
      id: 'sentence13',
      level: 5,
      isFinal: false,
      korean: '그래도 위험이 있어.',
      chinese: {
        hanzi: ['还是', '有', '风险'],
        pinyin: ['háishi', 'yǒu', 'fēngxiǎn'],
      },
    },
    {
      id: 'sentence13',
      level: 6,
      isFinal: true,
      korean: 'B: 내가 보기에는, 그래도 위험이 있어.',
      chinese: {
        hanzi: ['在', '我', '看来', '还是', '有', '风险'],
        pinyin: ['zài', 'wǒ', 'kànlai', 'háishi', 'yǒu', 'fēngxiǎn'],
      },
    },
    // 4번
    {
      id: 'sentence14',
      level: 1,
      isFinal: false,
      korean: '이 방안, 이 안',
      chinese: {
        hanzi: ['这', '个', '方案'],
        pinyin: ['zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 2,
      isFinal: false,
      korean: '이 방안에 동의하다.',
      chinese: {
        hanzi: ['同意', '这', '个', '方案'],
        pinyin: ['tóngyì', 'zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 3,
      isFinal: false,
      korean: '이 방안에 동의하지 않다.',
      chinese: {
        hanzi: ['不', '同意', '这', '个', '方案'],
        pinyin: ['bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 4,
      isFinal: false,
      korean: '이 방안에 동의하지 않는 거야?',
      chinese: {
        hanzi: ['不', '同意', '这', '个', '方案', '吗'],
        pinyin: ['bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn', 'ma'],
      },
    },
    {
      id: 'sentence14',
      level: 5,
      isFinal: true,
      korean: 'A: 당신은 이 방안에 동의하지 않나요?',
      chinese: {
        hanzi: ['你', '不', '同意', '这', '个', '方案', '吗'],
        pinyin: ['nǐ', 'bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn', 'ma'],
      },
    },
    {
      id: 'sentence14',
      level: 6,
      isFinal: false,
      korean: '한번 해보다, 시험 삼아 해보다.',
      chinese: {
        hanzi: ['试试'],
        pinyin: ['shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 7,
      isFinal: false,
      korean: '소규모로 한번 해보다.',
      chinese: {
        hanzi: ['小', '规模', '试试'],
        pinyin: ['xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 8,
      isFinal: false,
      korean: '먼저 소규모로 한번 해보다.',
      chinese: {
        hanzi: ['先', '小', '规模', '试试'],
        pinyin: ['xiān', 'xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 9,
      isFinal: false,
      korean: '먼저 소규모로 한번 해볼 수 있어요.',
      chinese: {
        hanzi: ['可以', '先', '小', '规模', '试试'],
        pinyin: ['kěyǐ', 'xiān', 'xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 10,
      isFinal: false,
      korean: '제 말은 먼저 소규모로 한번 해볼 수 있어요.',
      chinese: {
        hanzi: ['我', '的', '意思', '是', '可以', '先', '小', '规模', '试试'],
        pinyin: [
          'wǒ',
          'de',
          'yìsi',
          'shì',
          'kěyǐ',
          'xiān',
          'xiǎo',
          'guīmó',
          'shìshi',
        ],
      },
    },
    {
      id: 'sentence14',
      level: 11,
      isFinal: true,
      korean: 'B: 아니요, 제 말은 먼저 소규모로 한번 해볼 수 있다는 뜻이에요.',
      chinese: {
        hanzi: [
          '不是',
          '我',
          '的',
          '意思',
          '是',
          '可以',
          '先',
          '小',
          '规模',
          '试试',
        ],
        pinyin: [
          'bú shì',
          'wǒ',
          'de',
          'yìsi',
          'shì',
          'kěyǐ',
          'xiān',
          'xiǎo',
          'guīmó',
          'shìshi',
        ],
      },
    },
    // 5번
    {
      id: 'sentence15',
      level: 1,
      isFinal: false,
      korean: '이번 출장',
      chinese: {
        hanzi: ['这次', '出差'],
        pinyin: ['zhècì', 'chūchāi'],
      },
    },
    {
      id: 'sentence15',
      level: 2,
      isFinal: false,
      korean: '이번 출장 어때?',
      chinese: {
        hanzi: ['这次', '出差', '怎么样'],
        pinyin: ['zhècì', 'chūchāi', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence15',
      level: 3,
      isFinal: true,
      korean: 'A: 이번 출장 느낌은 어때?',
      chinese: {
        hanzi: ['这次', '出差', '感觉', '怎么样'],
        pinyin: ['zhècì', 'chūchāi', 'gǎnjué', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence15',
      level: 4,
      isFinal: false,
      korean: '얻은 게 많아(수확이 커).',
      chinese: {
        hanzi: ['收获', '大'],
        pinyin: ['shōuhuò', 'dà'],
      },
    },

    {
      id: 'sentence15',
      level: 5,
      isFinal: false,
      korean: '전반적으로 보면, 얻은 게 많아.',
      chinese: {
        hanzi: ['总的来说', '收获', '大'],
        pinyin: ['zǒng de lái shuō', 'shōuhuò', 'dà'],
      },
    },
    {
      id: 'sentence15',
      level: 6,
      isFinal: false,
      korean: '전반적으로 보면, 얻은 게 꽤 많아.',
      chinese: {
        hanzi: ['总', '的', '来', '说', '收获', '挺', '大', '的'],
        pinyin: ['zǒng', 'de', 'lái', 'shuō', 'shōuhuò', 'tǐng', 'dà', 'de'],
      },
    },

    {
      id: 'sentence15',
      level: 7,
      isFinal: true,
      korean: 'B: 전반적으로 보면, 얻은 게 그래도 꽤 많아.',
      chinese: {
        hanzi: ['总', '的', '来', '说', '收获', '还是', '挺', '大', '的'],
        pinyin: [
          'zǒng',
          'de',
          'lái',
          'shuō',
          'shōuhuò',
          'háishi',
          'tǐng',
          'dà',
          'de',
        ],
      },
    },
  ],
};

// 전역 변수로 내보내기
window.sentenceData = sentenceData;
